name: msml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - xgboost
      - lightgbm
      - mlflow
      - dagshub
