name: ML CI/CD Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn xgboost lightgbm imbalanced-learn seaborn matplotlib pandas

      - name: Run MLflow project (modelling.py)
        run: |
          mlflow run MLProject --env-manager=local

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: |
            MLProject/artefak/*.json
            MLProject/artefak/*.png
            MLProject/mlruns/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ftriaanggra/stroke-model:latest MLProject

      - name: Push Docker image
        run: docker push ftriaanggra/stroke-model:latest
